ERROR_INVALID_INPUT = "INVALID_INPUT"
ERROR_TRANSCRIPT_NOT_FOUND = "TRANSCRIPT_NOT_FOUND"
ERROR_DB_QUERY_FAILED = "DB_QUERY_FAILED"
ERROR_DB_WRITE_FAILED = "DB_WRITE_FAILED"
ERROR_VECTOR_SEARCH_FAILED = "VECTOR_SEARCH_FAILED"
ERROR_INGESTION_FAILED = "INGESTION_FAILED"
ERROR_EMBEDDING_FAILED = "EMBEDDING_FAILED"
ERROR_LLM_CALL_FAILED = "LLM_CALL_FAILED"
ERROR_LLM_PARSE_FAILED = "LLM_PARSE_FAILED"
ERROR_DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
ERROR_UNEXPECTED = "UNEXPECTED_ERROR"

__all__ = [
    "ERROR_DB_QUERY_FAILED",
    "ERROR_DB_WRITE_FAILED",
    "ERROR_DEPENDENCY_UNAVAILABLE",
    "ERROR_EMBEDDING_FAILED",
    "ERROR_INGESTION_FAILED",
    "ERROR_INVALID_INPUT",
    "ERROR_LLM_CALL_FAILED",
    "ERROR_LLM_PARSE_FAILED",
    "ERROR_TRANSCRIPT_NOT_FOUND",
    "ERROR_UNEXPECTED",
    "ERROR_VECTOR_SEARCH_FAILED",
]
